version: '3'

services:
  web:
    image: nginx:1.19.6
    volumes:
      - ./etc-nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80

  website:
    build: .
    env_file: .env
    depends_on:
      - database
      - broker
    # command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    # command: bash -c "python manage.py migrate && gunicorn config.wsgi -b 0.0.0.0:8000 --access-logfile -"
    command: gunicorn config.wsgi -b 0.0.0.0:8000 --access-logfile -
    expose:
      - 8000
    # volumes:
    #   - .:/usr/src

  worker:
    build: .
    env_file: .env
    depends_on:
      - database
      - broker
    command: celery --app config worker -l info

  database:
    image: postgres:10
    # restart: always
    env_file: .env
    expose:
      - 5432
    # ports:
    #   - 5432:5432
    volumes:
      - ~/.data/cinepolis:/var/lib/postgresql/data

  broker:
    image: redis:6.2
    # restart: always
    expose:
      - 6379

  redash-database:
    image: postgres:10
    environment:
      - POSTGRES_DB=redash
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    volumes:
      - ~/.data/redash:/var/lib/postgresql/data

  redash-broker:
    image: redis:6.2
    expose:
      - 6379

  redash:
    image: redash/redash:latest
    ports:
      - 5000:5000
    env_file: .env
    depends_on:
      - redash-database
      - redash-broker
