version: "3"

services:
  website:
    build: .
    env_file: .env
    depends_on:
      - database
      - broker
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${PORT}"
    ports:
      - 8000:${PORT}
    volumes:
      - .:/usr/src

  worker:
    build: .
    env_file: .env
    depends_on:
      - database
      - broker
    command: celery --app ${CELERY_APP} worker -l info

  database:
    image: postgres:10
    restart: always
    env_file: .env
    expose:
      - 5432
    volumes:
      - .data:/var/lib/postgresql/data

  broker:
    image: redis:6.2
    restart: always
    expose:
      - 6379
