# Generated by Django 3.1 on 2021-03-18 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('explorer', '0010_sql_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pivot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.query')),
            ],
        ),
    ]
