# Generated by Django 3.1 on 2021-03-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('city_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=50)),
                ('cinema_number', models.PositiveIntegerField()),
                ('city', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='cinepolis.city')),
            ],
        ),
    ]
