# Generated by Django 3.1 on 2021-03-08 07:03

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cinepolis', '0002_auto_20210308_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='city',
        ),
        migrations.AddField(
            model_name='billboardmovie',
            name='cinemas',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
