# Generated by Django 3.1 on 2021-03-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinepolis', '0004_delete_billboardmoviecinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboardrequest',
            name='response',
            field=models.JSONField(default=list),
        ),
    ]
