# Generated by Django 3.1 on 2021-03-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinepolis', '0006_city_tenant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboardrequest',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
