# Generated by Django 3.1 on 2021-03-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinepolis', '0009_auto_20210308_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billboardmovie',
            name='movie_number',
        ),
        migrations.AddField(
            model_name='billboardmovie',
            name='movie_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
