# Generated by Django 3.1 on 2021-03-11 05:10

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cinepolis', '0013_auto_20210310_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboardmovie',
            name='filter_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='billboardmovie',
            name='cinemas',
            field=models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='billboardmovie',
            name='movie_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
