# Generated by Django 3.1 on 2021-03-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinepolis', '0014_auto_20210310_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshowtime',
            name='session_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
