# Generated by Django 3.1 on 2021-03-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinepolis', '0015_auto_20210310_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieshowtime',
            name='cinema_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
