# Generated by Django 3.1 on 2021-03-08 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinepolis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillboardMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_number', models.PositiveIntegerField()),
                ('movie_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.CreateModel(
            name='BillboardRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('TO_DO', 'To Do'), ('DOING', 'Doing'), ('DONE', 'Done'), ('ERROR', 'Error')], default='TO_DO', max_length=5)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinepolis.city')),
            ],
        ),
        migrations.CreateModel(
            name='BillboardMovieCinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_number', models.PositiveIntegerField()),
                ('cinema_name', models.CharField(max_length=50)),
                ('billboard_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinepolis.billboardmovie')),
            ],
        ),
        migrations.AddField(
            model_name='billboardmovie',
            name='billboard_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinepolis.billboardrequest'),
        ),
    ]
