# Generated by Django 3.1 on 2021-03-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinepolis', '0005_billboardrequest_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='tenant_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
