# Generated by Django 3.1 on 2021-03-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinepolis', '0007_billboardrequest_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='billboard_section',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
