# Generated by Django 3.1 on 2021-03-11 03:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinepolis', '0012_auto_20210309_2332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillboardRequest',
            new_name='Billboard',
        ),
        migrations.RenameField(
            model_name='billboardmovie',
            old_name='billboard_request',
            new_name='billboard',
        ),
        migrations.AddField(
            model_name='billboardmovie',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billboardmovie',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='billboardmovie',
            name='response',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='billboardmovie',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'To Do'), ('DOING', 'Doing'), ('DONE', 'Done'), ('ERROR', 'Error')], default='TO_DO', max_length=5),
        ),
        migrations.AddField(
            model_name='billboardmovie',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='MovieShowtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_code', models.CharField(blank=True, max_length=5)),
                ('session_code', models.CharField(blank=True, max_length=5)),
                ('showtime', models.DateTimeField()),
                ('screen_number', models.CharField(blank=True, max_length=5)),
                ('screen_name', models.CharField(blank=True, max_length=50)),
                ('billboard_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinepolis.billboardmovie')),
            ],
        ),
    ]
