# Generated by Django 3.1 on 2021-03-12 05:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinepolis', '0016_movieshowtime_cinema_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=5)),
                ('status_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='billboardmovie',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.RenameField(
            model_name='billboard',
            old_name='status',
            new_name='request_status',
        ),
        migrations.RenameField(
            model_name='billboardmovie',
            old_name='status',
            new_name='request_status',
        ),
        migrations.AddField(
            model_name='billboard',
            name='access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movieshowtime',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movieshowtime',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movieshowtime',
            name='request_status',
            field=models.CharField(choices=[('TO_DO', 'To Do'), ('DOING', 'Doing'), ('DONE', 'Done'), ('ERROR', 'Error')], default='TO_DO', max_length=5),
        ),
        migrations.AddField(
            model_name='movieshowtime',
            name='response',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='movieshowtime',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='MovieShowtimeSeatStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(blank=True, max_length=5)),
                ('status_name', models.CharField(blank=True, max_length=20)),
                ('seat_count', models.IntegerField(default=0)),
                ('movie_showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinepolis.movieshowtime')),
            ],
        ),
    ]
