# Generated by Django 3.1 on 2021-03-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinepolis', '0017_auto_20210311_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seatstatus',
            options={'verbose_name_plural': 'Seat Statuses'},
        ),
        migrations.AddField(
            model_name='movieshowtime',
            name='version_details',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
